# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_ideatag'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(to='ideas.IdeaTag'),
        ),
    ]
