# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_idea_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='idea_details',
            field=models.CharField(default='Filler', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_text',
            field=models.CharField(max_length=50),
        ),
    ]
